# .github/workflows/chromatic.yml

name: 'Chromatic'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Build Storybook
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: nuxt storybook build
      - name: Publish to Chromatic
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: chromatic --project-token ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
